### ISSUE TITLE
react-native-video-controls

### ISSUE THREAD

**Issue by criszz77** [FezMLG/AniWatch#6]
Hey there @FezMLG 

I noticed that you're using [react-native-video-controls](https://github.com/itsnubix/react-native-video-controls). I'm the author of [react-native-media-console](https://github.com/criszz77/react-native-media-console) which is basically a rewrite with TypeScript of `react-native-video-controls`. And I also fixed all the issues and bugs I could find. If this helped you, please help us back with a star! ⭐️ Thanks

Cheers

**Comment by FezMLG** [comment]
Thanks for reaching out. I checked it out and its pretty good. It will be added it in future release.
